### ISSUE TITLE
Getting Started Question

### ISSUE THREAD

**Issue by arleym** [dynek/crashplan-qpkg#11]
Hello! I have the qpkg installed and on, but when I go to "Open" it asks me to login. Neither my Qnap admin nor Crashplan accounts work. No idea what to do. Everything is up to date.

**Comment by jasonsf** [comment]
I believe that login is unique to that admin screen. You have to create a new one. It is only useful if you want to change the network interface that crashplan listens on or to download the log files. To configure crashplan you have to use the desktop client and change the ip address it talks to in the config file.

**Comment by arleym** [comment]
Do you know where I could ind more info on where to change the IP address? I'm assuming this won't mean my desktop needs to be on to backup the server!

**Comment by jasonsf** [comment]
This post has instructions: http://forum.qnap.com/viewtopic.php?f=227&t=39078

You don't have to have your desktop on to backup, but you do need it on to configure the backup service.  Then you can set the config back to pointing to the crashplan service on your desktop and forget about it.

**Comment by dynek** [comment]
Hello,

I'd like to keep this space for issues related to the QPKG itself, not its use.
Reason why I'm closing this issue.

Please head to QNAP's forum for questions related to installation and use of the QPKG

Thank you.
