### ISSUE TITLE
New version ?

### ISSUE THREAD

**Issue by butcher666** [dynek/crashplan-qpkg#12]
Hallo dynek

Dont know if you noticed but CP has release version 4.2 for windows

/Butcher

**Comment by dynek** [comment]
huh we're quite far from what could be said to be an up to date version.. are we still running 3.7.0 ?!
How come they jumped from 3.7 to 4.2. Anyways it's gonna be on my todo list now :-)

Thanks!

**Comment by dynek** [comment]
Mind giving it a shot with the version that corresponds to your arch?

https://www.dropbox.com/s/eoyaidxd9je6sxx/CrashPlan_4.2.0_35_arm-x09.qpkg?dl=1
https://www.dropbox.com/s/9twd05pnomlufvk/CrashPlan_4.2.0_35_arm-x19.qpkg?dl=1
https://www.dropbox.com/s/nbmjyg3z4ql6v4z/CrashPlan_4.2.0_35_arm-x31.qpkg?dl=1
https://www.dropbox.com/s/skd0qimpa0ws6fv/CrashPlan_4.2.0_35_x86.qpkg?dl=1

Thanks

**Comment by dynek** [comment]
Anyways.. released :-)

http://forum.qnap.com/viewtopic.php?f=227&t=39078
