### ISSUE TITLE
Crashplan 4.3 Support

### ISSUE THREAD

**Issue by martindsouza** [dynek/crashplan-qpkg#14]
I have Crashplan 4.3 on OS X which uses the new `.ui_info` file format ([outlined here](http://support.code42.com/CrashPlan/Latest/Configuring/Using_CrashPlan_On_A_Headless_Computer#Locations_Of_.ui_info_On_All_Operating_Systems))

As per the comments on [this blog post](http://orawik.blogspot.ca/2012/08/set-up-crashplan-on-qnap-nas-using-qpkg.html) I downloaded the configuration files from the QNAP Crashplan app but it does not contain the `.ui_info` files, rather the old `ui.properties`.

Will a new version be released to support this?

**Comment by dynek** [comment]
Hello,

The QPKG has been updated to the version containing the ui_info file when release 36 was made: https://github.com/dynek/crashplan-qpkg/commit/4145cf810ce567473a97ef2102401085bae68566

You may head to the QNAP forum to ask questions if not yet done: http://forum.qnap.com/viewforum.php?f=227

Hope this helps!
