### ISSUE TITLE
manually starting crashplan via /etc/init.d/crashplan.sh exits crashplan on shell exit

### ISSUE THREAD

**Issue by finsterwalder** [dynek/crashplan-qpkg#15]
When crashplan is not running and I ssh to my qnap and execute "/etc/init.d/crashplan.sh start", crashplan is started. But when I exit the shell, crashplan stops.

I have a QNAP TS-231+ with the current OS: QTS 4.2.0

**Comment by dynek** [comment]
Hello,

That's expected and totally normal on ARM-based NAS. Service should be started from QNAP's admin web interface.

Cheers
