### ISSUE TITLE
HELP!! Adopt doesn't work....

### ISSUE THREAD

**Issue by paradoxgrowth** [dynek/crashplan-qpkg#18]
Hi Dynek!

First, thank you for taking the time to create this package. You are so awesome to take the time to create and maintain this!

In the past I was able to adopt a backup using your package and actually have been plugging along just fine for almost a year. However, I wake up one morning last week and I can't attach to crash plan interface via client (headless of course) no matter what I try. I check with crash plan and it says that my qnap has not been backing up for days. After playing with it and trying several times to get it back up I decided to reinstall the package. Now it seems like it works but when I choose adopt my previous backup, it tries to update itself and then crashes never to be seen again. 

I can't start all over, it would make me erase everything from crash plan, of which I don't have copies of somethings. 2nd, there is 4 TB up there and that would take me months to throw back. What can I do? Is there some way to prevent it from trying to update? Or trick it into thinking that it doesn't need to update? 

Thank you so much for your help!

**Comment by toledobastos** [comment]
QNAP's CrashPlan app no longer works since the release of June 12. It's part of the regular routine: CrashPlan updates the service and the QNAP CP app ceases to work. Dynek goes back to the code and amend it to work with the new version (a Sisyphus task, to be sure). There's no solution to this updating problem that I know of.

**Comment by paradoxgrowth** [comment]
Toledobastos,
Thanks for the info. Oddly mine was working great until last week. 

Dynek, thanks for all your hard work. I really hope you can figure out how to adopt. I'm sure many like myself are in the same boat.

**Comment by dynek** [comment]
Hello,

June 12th? Wasn't it July?

Anyways, version 44 on the forum fixes the upgrade problem. However as stated in the main thread, Entware-ng has to be installed prior to CrashPlan's reinstallation.

Cheers

**Comment by paradoxgrowth** [comment]
Hi Dynek,

Thank you for taking the time to answer. You are correct, mine stopped in july without having Entware-ng. Now I see what you are referring to, I have installed it but it still doesn't work. I still have the same result.

With Entware-ng installed, I installed crash plan (from scratch). I am able to connect to it just fine with my client (via headless). I sign in and choose adopt so I can take up where I left off. Choosing adopt allows you to take your backup from another computer and let the current computer take it over. In this case I am taking the previous NAS crashplan backup installation and trying to use the same NAS to continue on. After I choose adopt, Crashplan on my computer client (headless) contacting the NAS says ''updating" then crashes. Looking at the NAS the crash plan info page gives a 404 error. After stopping and restarting the crash plan app on the NAS the configuration page or site comes back online but my client computer (headless) contacting the NAS says it can't connect to the crash plan engine. I go to the crash plan website to see if the NAS is connected and backing up to crash plan, and it says it not connected. To me it seems like when I choose adopt a backup, it makes crash plan upgrade the NAS software which is causing it to crash. 

Am I doing this wrong? Thank you for your help and thank you for taking on the daunting task of coding and maintaining the qnap version of crashplan! For this and your continuous help, myself and many others are extremely grateful!

**Comment by paradoxgrowth** [comment]
I have excellent news. I after uninstalling EVERYTHING (Crashplan, Java 8, Entware-ng), then reinstalling everything, it works! I even got it to adopt! Dynek, you are a genius! I am so glad you got adopt to work!!!! Thank you for your help! :)

**Comment by dynek** [comment]
No problem :-) Glad it now works for you!
