### ISSUE TITLE
Cannot reconnect after update

### ISSUE THREAD

**Issue by jaredcorso** [dynek/crashplan-qpkg#19]
DId a fresh install of the qpkg, initially I can connect from a desktop client to the NAS/qpkg.  After starting a backup the application updates and then I am no longer able to connect. I verified key, ip and port are correct.  My guess is this is a version mismatch between the qpkg and the desktop client?

**Comment by dynek** [comment]
Which version did you install? (last two digits in QPKG filename)

**Comment by jaredcorso** [comment]
43

On Mon, Jul 18, 2016 at 11:36 AM, Pierrick Brossin <notifications@github.com

**Comment by dynek** [comment]
I release v44 in the forums. It now required entware-ng to be installed. Details here: https://forum.qnap.com/viewtopic.php?f=227&t=39078

**Comment by jaredcorso** [comment]
Will give that a shot, closing the  issue. Thanks!

On Mon, Jul 18, 2016 at 11:41 AM, Pierrick Brossin <notifications@github.com

**Comment by jaredcorso** [comment]
Can confirm the updated version 44 worked.  Are you planning on publishing the updated version to the app center? the app center still has version 43.

**Comment by dynek** [comment]
Hey Jared, sorry for the late reply. I will request QNAP to update the QPKG in the App Center.
