### ISSUE TITLE
Workaround fails due to missing java.patched

### ISSUE THREAD

**Issue by micoon012** [dynek/crashplan-qpkg#21]
Hey Dynek,

thank you for providing an up-to-date crashplan package. It seems you put quite some effort in it.

I found your post in the Qnap Forum about the "[QPKG] CrashPlan v4.8.0 NOW REQUIRES Entware-ng" (https://forum.qnap.com/viewtopic.php?f=227&t=39078). Unfortunately the Dropbox links are not working anymore, hence, I could not get the qpkg for CP 4.8 x86. So I downloaded the code from GitHub and built the package myself. However, I cannot get it to work since the crashplan.sh fails when trying to attemp the workaround for versions >4.5. It is missing the patched java file. I don't know how to patch the java. Could you give me a hint on how to troubleshoot? And/or could you provide the qpkg package?

Thank you very much in advance

p.s.: I have a TS-451+ with kernel 3.12.6 and glibc 2.6.1

**Comment by dynek** [comment]
Just fixed the links - Sorry for that. I had some issue with Dropbox lately.

Latest QPKG should work OK with x86 devices. Let me know.

**Comment by micoon012** [comment]
Thank you. It works. Backup is already running.
