### ISSUE TITLE
QNAP 4.3 Beta x64

### ISSUE THREAD

**Issue by AlexMihe** [dynek/crashplan-qpkg#22]
Hello,

Would anyone have an idea when Crashplan QPKG will be made compatible with QNAP 4.3 ?

Thank you in advance for your help.

And thank you very much for your work !!!

Best reagards.

**Comment by dynek** [comment]
Hello @AlexMihe,

The problem I have with 4.3 is that it's still beta :-/

Unfortunately I only have one x86 NAS currently and I don't feel like installing beta software as I heavily rely on it for multiple purposes.

As soon it's production ready I'll port it.

Most likely, it will become x86 + 64-bits only.
Other architectures are too complicated (or even impossible) to maintain.

Sorry for that.

**Comment by AlexMihe** [comment]
Hello @dynek ,

Thank you for your answer !

Hope it will be in production soon :-)

Thanks again !!!
