### ISSUE TITLE
PATH_TO_JAVA / JAVACOMMON at build-time or at install-time?

### ISSUE THREAD

**Issue by ProBackup-nl** [dynek/crashplan-qpkg#29]
Currently PATH_TO_JAVA a.k.a. JAVACOMMON is determined at build-time.

Shouldn't this be determined at install-time?

Or is the `java` command at exactly the same location for each and every QNAP device?

**Comment by dynek** [comment]
That makes sense. My laptop died few days back and I'll be quite slow at answering until I fix it or buy a new one. Time to put the mainboard in the oven :-)

**Comment by ProBackup-nl** [comment]
I hope you have got a working backup. Good luck with your "roasting".

**Comment by dynek** [comment]
I do :-) trustworthy ssh came to the rescue and I was able to rsync everything (well the missing bits) before the GPU "died".

**Comment by dynek** [comment]
OK so the motherboard went inside the oven and it resurrected my MacBook (not kidding at all).

I am currently updating the QPKG to work with 64-bit and implemented the fix - commit to come.
