### ISSUE TITLE
Why have symbolic linked folders 'arm-x09' and 'arm-x41'?

### ISSUE THREAD

**Issue by ProBackup-nl** [dynek/crashplan-qpkg#35]
@dynek 
I see that there as symlinked folders in [crashplan-qpkg/src/qpkg/](https://github.com/dynek/crashplan-qpkg/tree/master/src/qpkg) named 'arm-x09' ([that points to 'arm-x19'](https://github.com/dynek/crashplan-qpkg/blob/master/src/qpkg/arm-x09)) and 'arm-x41' ([that points to 'arm-x31'](https://github.com/dynek/crashplan-qpkg/blob/master/src/qpkg/arm-x41)).

The generated/created/build .qpkg package files are not identical packages:
```
MD5 (CrashPlan_2011_1.16_arm-x09.qpkg) = e1caafa284b175272b3411e7fe169bf7
MD5 (CrashPlan_2011_1.16_arm-x19.qpkg) = a2a02930a297bbfe3bbf64356ffff7cb
MD5 (CrashPlan_2011_1.16_arm-x31.qpkg) = 8131a3c4f0afb6b9a476e6ae45d21aef
MD5 (CrashPlan_2011_1.16_arm-x41.qpkg) = df705daae278b62c8bf6b6b1513b643e
```
What are the differences between the generated:

1.   '**..._arm-x09.qpkg**' and '**..._arm-x19.qpkg**'
2.   '**..._arm-x41.qpkg**' and '**..._arm-x31.qpkg**'
?

For which purpose were these symbolic linked folders ever created?

--- 
QNAP architectures to my knowlege:

1. `x86` for platformID `TS-NASX86`
 - except `ce53xx` for `TS-269H` (I don't understand why this Celeron isn't `x86`)
2. `arm_kw` for platformID `TS-NASARM` (your soft-float`x09` and `x19` mappings, my guess for ARMv5)
 - except `arm_ms` for platformID `TS-X31` and `TS-X31U` (ARMv7 with vfpv3 only)
 - except `arm_al` for platformID `TS-X31X`, `TS-X31XU`, `TS-X35`, `TS-X41`, `TS-531P`, `TAS-X68` and `TS-X28` (**A**nnapurna**L**abs ARMv7 with both vfpv3 and vfpv4)

partly sourced from [https://wiki.qnap.com/wiki/Filesystem_not_clean](https://wiki.qnap.com/wiki/Filesystem_not_clean)

**Comment by dynek** [comment]
Hello,

The resulting QPKG won't be any different between x09 and x19 (for instance) because same files will be used. Hash will differ though because the name/word "x09" / "x19" must be mentioned somewhere in the deployment script.

**Comment by dynek** [comment]
ARM is not supported anymore.
