### ISSUE TITLE
URL /crashplan/ was not found

### ISSUE THREAD

**Issue by ChrisColotti** [dynek/crashplan-qpkg#36]
I have a newly configured QNAP TVS-671 with 4.3.3.  I installed the required packages before installing Crashplan.  The web server is enabled as I am using it for some testing, but the QPKG does not create the /crashplan/ directory on the /web folder.  Therefore I cannot see the configuration details.  How can I get the page to show up so I can get the configuration information?

Even if I create it manually remove and reinstall all I get is a 403 error.  I've removed and reinstalled multiple times with the same issue and this is a brand new 4.3.3 build.

**Comment by dynek** [comment]
Hello @ChrisColotti,

The symlink is created by the init-script: https://github.com/dynek/crashplan-qpkg/blob/master/src/qpkg/shared/crashplan.sh#L164

If it's not created that means a condition surrounding this instruction skips this step.
Are you able to investigate / do you have linux skills?

This web interface has been source of many trouble/exchanges and I'd like to integrate it inside QTS but QNAP remains very quiet on how it can be done.

Thank you

**Comment by ChrisColotti** [comment]
I do have some linux skills.  Can we add the symlink manually or re-run the script?

**Comment by ChrisColotti** [comment]
I was able to connect and start backing up....so it is working after the manual steps....

**Comment by dynek** [comment]
Can't do much more then.
